"""
Context builder service — the key integration point between IntentFoundry
and AI agent runners.

Takes a set of specs, ADRs, and bounded context constraints and assembles
a formatted context package ready for injection into an AI agent prompt.

Output formats:
  - markdown : human-readable, works with most LLMs
  - json     : structured, for programmatic consumption
  - yaml     : for config-style toolchains
"""
import json
from datetime import UTC, datetime
from typing import Any

import yaml
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.domain import ADR, ADRStatus, BoundedContext, FitnessFunction, Spec
from app.schemas.schemas import AIContextRequest, AIContextResponse


# Rough token estimate: 1 token ≈ 4 characters
_CHARS_PER_TOKEN = 4


class ContextBuilderService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    async def build(
        self,
        project_id: str,
        request: AIContextRequest,
    ) -> AIContextResponse:
        """
        Assemble an AI-ready context package.

        The output is the formatted string that gets prepended to an
        AI agent prompt — it gives the agent everything it needs to
        build within the project's architectural and specification constraints.
        """
        # 1. Load specs
        specs = await self._load_specs(request.spec_ids)

        # 2. Load ADRs — either explicit list or auto-selected from spec links
        adr_ids = request.adr_ids
        if adr_ids is None:
            # Auto-select: union of all linked_adr_ids across the specs
            linked = set()
            for spec in specs:
                linked.update(spec.linked_adr_ids or [])
            adr_ids = list(linked)

        adrs = await self._load_adrs(adr_ids, project_id) if adr_ids else []

        # 3. Load bounded context
        bounded_context = None
        if request.bounded_context_id:
            bc_result = await self.db.execute(
                select(BoundedContext).where(
                    BoundedContext.id == request.bounded_context_id,
                    BoundedContext.project_id == project_id,
                )
            )
            bounded_context = bc_result.scalar_one_or_none()

        # 4. Load fitness constraints summary
        fitness_constraints: list[str] = []
        if request.include_fitness_constraints:
            ff_result = await self.db.execute(
                select(FitnessFunction).where(
                    FitnessFunction.project_id == project_id,
                    FitnessFunction.is_active.is_(True),
                    FitnessFunction.deleted_at.is_(None),
                )
            )
            ffs = ff_result.scalars().all()
            fitness_constraints = [
                f"[{ff.severity.value.upper()}] {ff.name}: {ff.description or ff.check_type}"
                for ff in ffs
            ]

        # 5. Format the package
        fmt = request.format
        if fmt == "markdown":
            package = _render_markdown(specs, adrs, bounded_context, fitness_constraints)
        elif fmt == "json":
            package = _render_json(specs, adrs, bounded_context, fitness_constraints)
        else:  # yaml
            package = _render_yaml(specs, adrs, bounded_context, fitness_constraints)

        token_estimate = len(package) // _CHARS_PER_TOKEN

        return AIContextResponse(
            project_id=project_id,
            context_package=package,
            spec_count=len(specs),
            adr_count=len(adrs),
            fitness_constraint_count=len(fitness_constraints),
            token_estimate=token_estimate,
            generated_at=datetime.now(UTC),
        )

    async def _load_specs(self, spec_ids: list[str]) -> list[Spec]:
        if not spec_ids:
            return []
        result = await self.db.execute(
            select(Spec).where(Spec.id.in_(spec_ids), Spec.deleted_at.is_(None))
        )
        return list(result.scalars().all())

    async def _load_adrs(self, adr_ids: list[str], project_id: str) -> list[ADR]:
        result = await self.db.execute(
            select(ADR).where(
                ADR.id.in_(adr_ids),
                ADR.project_id == project_id,
                ADR.status.in_([ADRStatus.ACCEPTED, ADRStatus.PROPOSED]),
                ADR.deleted_at.is_(None),
            )
        )
        return list(result.scalars().all())


# ─── Format renderers ─────────────────────────────────────────────────────────

def _render_markdown(
    specs: list[Spec],
    adrs: list[ADR],
    bounded_context: BoundedContext | None,
    fitness_constraints: list[str],
) -> str:
    sections: list[str] = []

    sections.append("# IntentFoundry Context Package")
    sections.append(
        "> This context package is auto-generated by IntentFoundry. "
        "It contains the specifications, architectural decisions, and constraints "
        "that govern what you should build. Build within these boundaries — "
        "do not invent alternatives unless explicitly asked.\n"
    )

    # Bounded context
    if bounded_context:
        sections.append("## Bounded Context\n")
        sections.append(f"**Name:** {bounded_context.name}\n")
        if bounded_context.description:
            sections.append(f"{bounded_context.description}\n")
        if bounded_context.includes:
            sections.append(f"**Includes:**\n{bounded_context.includes}\n")
        if bounded_context.excludes:
            sections.append(
                f"**Excludes (do NOT implement these):**\n{bounded_context.excludes}\n"
            )
        if bounded_context.interfaces:
            sections.append(
                f"**External interfaces:**\n```json\n"
                f"{json.dumps(bounded_context.interfaces, indent=2)}\n```\n"
            )

    # Specifications
    if specs:
        sections.append("## Specifications\n")
        sections.append(
            "The following specifications define what you must build. "
            "Every acceptance criterion must be satisfied.\n"
        )
        for spec in specs:
            sections.append(f"### {spec.title} ({spec.format.value.upper()})\n")
            content = spec.content

            if spec.format.value == "bdd" and content.get("bdd_scenarios"):
                for scenario in content["bdd_scenarios"]:
                    sections.append(f"**Scenario:** {scenario.get('title', '')}\n")
                    for step in scenario.get("given", []):
                        sections.append(f"- Given {step}")
                    for step in scenario.get("when", []):
                        sections.append(f"- When {step}")
                    for step in scenario.get("then", []):
                        sections.append(f"- Then {step}")
                    sections.append("")

            elif spec.format.value == "cdc" and content.get("cdc_contracts"):
                for contract in content["cdc_contracts"]:
                    sections.append(
                        f"**{contract.get('method')} {contract.get('path')}**"
                    )
                    sections.append(
                        f"```json\n{json.dumps(contract, indent=2)}\n```\n"
                    )

            elif spec.format.value == "example" and content.get("example_tables"):
                for table in content["example_tables"]:
                    if table.get("description"):
                        sections.append(f"*{table['description']}*\n")
                    cols = " | ".join(table.get("columns", []))
                    sep = " | ".join(["---"] * len(table.get("columns", [])))
                    sections.append(f"| {cols} |")
                    sections.append(f"| {sep} |")
                    for row in table.get("rows", []):
                        sections.append(f"| {' | '.join(str(v) for v in row)} |")
                    sections.append("")

            else:
                if content.get("free_text"):
                    sections.append(content["free_text"])

            if content.get("acceptance_criteria"):
                sections.append("\n**Acceptance criteria:**")
                for criterion in content["acceptance_criteria"]:
                    sections.append(f"- {criterion}")

            if content.get("out_of_scope"):
                sections.append("\n**Out of scope (do not implement):**")
                for item in content["out_of_scope"]:
                    sections.append(f"- {item}")
            sections.append("")

    # Architecture decisions
    if adrs:
        sections.append("## Architecture Decisions\n")
        sections.append(
            "The following ADRs are active constraints. "
            "Build within these decisions — they represent deliberate architectural choices.\n"
        )
        for adr in adrs:
            sections.append(f"### ADR-{adr.number:03d}: {adr.title}\n")
            sections.append(f"**Status:** {adr.status.value}")
            sections.append(f"\n**Decision:** {adr.decision}\n")
            sections.append(f"**Consequences:** {adr.consequences}\n")
            if adr.alternatives_considered:
                sections.append(
                    f"**Alternatives rejected:** {adr.alternatives_considered}\n"
                )

    # Fitness constraints
    if fitness_constraints:
        sections.append("## Architectural Constraints (Fitness Functions)\n")
        sections.append(
            "The following constraints are automatically verified in CI. "
            "Your output must satisfy all ERROR-level constraints.\n"
        )
        for constraint in fitness_constraints:
            sections.append(f"- {constraint}")
        sections.append("")

    sections.append(
        "---\n*End of IntentFoundry context package. "
        "Build what is specified. Nothing more, nothing less.*"
    )
    return "\n".join(sections)


def _render_json(
    specs: list[Spec],
    adrs: list[ADR],
    bounded_context: BoundedContext | None,
    fitness_constraints: list[str],
) -> str:
    data: dict[str, Any] = {
        "intentfoundry_context": {
            "generated_at": datetime.now(UTC).isoformat(),
            "bounded_context": None,
            "specs": [],
            "adrs": [],
            "fitness_constraints": fitness_constraints,
        }
    }
    if bounded_context:
        data["intentfoundry_context"]["bounded_context"] = {
            "name": bounded_context.name,
            "description": bounded_context.description,
            "includes": bounded_context.includes,
            "excludes": bounded_context.excludes,
            "interfaces": bounded_context.interfaces,
        }
    for spec in specs:
        data["intentfoundry_context"]["specs"].append({
            "title": spec.title,
            "format": spec.format.value,
            "content": spec.content,
        })
    for adr in adrs:
        data["intentfoundry_context"]["adrs"].append({
            "number": adr.number,
            "title": adr.title,
            "status": adr.status.value,
            "decision": adr.decision,
            "consequences": adr.consequences,
        })
    return json.dumps(data, indent=2, default=str)


def _render_yaml(
    specs: list[Spec],
    adrs: list[ADR],
    bounded_context: BoundedContext | None,
    fitness_constraints: list[str],
) -> str:
    data: dict[str, Any] = json.loads(
        _render_json(specs, adrs, bounded_context, fitness_constraints)
    )
    return yaml.dump(data, default_flow_style=False, allow_unicode=True)
